"""
cosine_sim_ext_cifar100.py – Build per-class sample-affinity matrices on GPU.

Replaces the chunked numpy cosine with a single batched torch matmul on GPU:
    A = F.normalize(X, dim=1) @ F.normalize(X, dim=1).T
This is ~10–50× faster than the chunked CPU version for large feature vectors.
"""

import os
import numpy as np
import torch
import torch.nn.functional as F

from config import ACTIVATIONS_DIR, AFFINITY_DIR, NUM_CLASSES, LAYERS

device      = torch.device("cuda" if torch.cuda.is_available() else "cpu")
MAX_SAMPLES = 50

MODELS = {
    # "conv2net": LAYERS["conv2net"],
    # "conv6net": LAYERS["conv6net"],
    "vgg16":    LAYERS["vgg16"],
}


def cosine_matrix_gpu(x: np.ndarray) -> np.ndarray:
    """
    (N, F) numpy array  →  (N, N) cosine similarity matrix computed on GPU.
    Falls back to CPU for very small inputs where GPU overhead isn't worth it.
    """
    t  = torch.tensor(x, dtype=torch.float32, device=device)
    t  = F.normalize(t, dim=1)          # unit-norm rows
    mat = (t @ t.T).cpu().numpy()        # single matmul on GPU
    return mat.astype(np.float32)


for model_name, layer_names in MODELS.items():
    model_dir = os.path.join(ACTIVATIONS_DIR, model_name)
    if not os.path.isdir(model_dir):
        print(f"⚠  No activations for {model_name} — skipping"); continue

    save_dir = os.path.join(AFFINITY_DIR, model_name)
    os.makedirs(save_dir, exist_ok=True)

    for class_id in range(NUM_CLASSES):
        class_dir = os.path.join(model_dir, f"class_{class_id}")
        if not os.path.isdir(class_dir):
            continue

        files = [f for f in os.listdir(class_dir) if f.endswith(".pt")]
        correct_data, incorrect_data = [], []

        for fname in files:
            # Activation files are generated by activation_ext_cifar100.py as
            # pickled dictionaries, not plain weight tensors. PyTorch 2.6+
            # defaults torch.load(..., weights_only=True), which cannot read
            # these pickle-protocol-4 files.
            d = torch.load(
                os.path.join(class_dir, fname),
                map_location="cpu",
                weights_only=False,
            )
            if d["correct"] and len(correct_data) < MAX_SAMPLES:
                correct_data.append(d)
            elif not d["correct"] and len(incorrect_data) < MAX_SAMPLES:
                incorrect_data.append(d)
            if len(correct_data) >= MAX_SAMPLES and len(incorrect_data) >= MAX_SAMPLES:
                break

        for split, data in [("correct", correct_data), ("incorrect", incorrect_data)]:
            aff = {}
            for layer in layer_names:
                vecs = [d["activations"][layer].flatten().numpy()
                        for d in data if layer in d["activations"]]
                if not vecs:
                    continue
                mat = np.stack(vecs)
                aff[layer] = (cosine_matrix_gpu(mat)
                               if mat.shape[0] > 1 else np.array([[1.0]]))
            np.save(os.path.join(save_dir, f"class_{class_id}_{split}.npy"),
                    aff, allow_pickle=True)

        torch.cuda.empty_cache()
        print(f"{model_name:10s} class {class_id:3d}  "
              f"correct={len(correct_data)}  incorrect={len(incorrect_data)}")

print("\nAffinity matrices saved to", AFFINITY_DIR)
