"""
pg_ext_cifar100.py – Compute PG1 diffusion eigenvectors entirely on GPU.

Key GPU upgrades vs the CPU version:
  • Cosine affinity matrix  →  torch F.normalize + batched matmul on CUDA
  • Diffusion operator      →  torch tensor ops on CUDA
  • Eigendecomposition      →  torch.linalg.eigh on CUDA  (replaces scipy eigh)

joblib parallelism is removed: sequential GPU ops are faster than forked CPU
workers when the GPU is available, and CUDA + fork = undefined behaviour.
"""

import os, time, random, csv
import numpy as np
import torch
import torch.nn.functional as F

from config import ACTIVATIONS_DIR, PG_DIR, NUM_CLASSES, PG_FC_LAYER

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"PG extraction device: {device}")

ALPHA  = 0.5
T      = 0.5
SIGMA  = 0.1

MODELS = {
    "conv2net": [PG_FC_LAYER["conv2net"]],
    # "conv6net": [PG_FC_LAYER["conv6net"]],
    # "vgg16":    [PG_FC_LAYER["vgg16"]],
}


# ── GPU cosine affinity ────────────────────────────────────────
def cosine_affinity_gpu(X_np: np.ndarray, sigma: float = SIGMA) -> torch.Tensor:
    """
    X_np : (units, features)
    Returns (units, units) Gaussian affinity on GPU.
    """
    X   = torch.tensor(X_np, dtype=torch.float32, device=device)
    X   = F.normalize(X, dim=1)
    cos = X @ X.T                                    # (units, units)
    A   = torch.exp(-(1 - cos) ** 2 / (2 * sigma ** 2))
    A   = A + 1e-6
    A   = (A + A.T) / 2
    A.diagonal().add_(1e-10)
    return A


# ── GPU diffusion PG1 ─────────────────────────────────────────
def diffusion_pg1_gpu(A: torch.Tensor,
                      alpha: float = ALPHA,
                      t:     float = T,
                      eps:   float = 1e-10,
                      jitter: float = 1e-6) -> np.ndarray:
    """
    Compute PG1 (scaled second eigenvector of diffusion operator) on GPU.
    A : (units, units) symmetric affinity tensor already on device.
    Returns numpy array of shape (units,).
    """
    if A.shape[0] == 1:
        return np.array([1.0])

    A = (A + A.T) / 2
    A = torch.where(A == 0, torch.full_like(A, jitter), A)

    d       = A.sum(dim=1)                           # (units,)
    d_alpha = d.clamp(min=eps) ** alpha
    D_inv   = torch.diag(1.0 / d_alpha)
    K       = D_inv @ A @ D_inv
    row_sum = K.sum(dim=1, keepdim=True).clamp(min=eps)
    M       = K / row_sum                            # row-stochastic

    if torch.isnan(M).any() or torch.isinf(M).any():
        M = M + jitter * torch.rand_like(M)

    # torch.linalg.eigh returns eigenvalues in ascending order
    eigvals, eigvecs = torch.linalg.eigh(M.double())  # double for stability
    # second-largest: index -2
    pg1 = eigvecs[:, -2] * (eigvals[-2] ** t)
    return pg1.float().cpu().numpy()


# ── Main extraction loop ───────────────────────────────────────
def process(model_name, split, class_id, layer_name):
    class_dir = os.path.join(ACTIVATIONS_DIR, model_name, f"class_{class_id}")
    if not os.path.isdir(class_dir):
        return "missing"

    files = [f for f in os.listdir(class_dir) if f.endswith(".pt")]
    random.shuffle(files)

    acts = None
    for fname in files:
        # Activation files are generated by activation_ext_cifar100.py as
        # pickled dictionaries, not plain weight tensors. PyTorch 2.6+
        # defaults torch.load(..., weights_only=True), which cannot read
        # these pickle-protocol-4 files.
        d  = torch.load(
            os.path.join(class_dir, fname),
            map_location="cpu",
            weights_only=False,
        )
        ok = d.get("correct", False)
        if (split == "correct" and ok) or (split == "incorrect" and not ok):
            if layer_name in d["activations"]:
                acts = d["activations"][layer_name].flatten().numpy()[None, :]
                break

    if acts is None:
        return "no_samples"

    units = acts.shape[1]

    if units == 1:
        pg1 = np.array([1.0])
    else:
        A   = cosine_affinity_gpu(acts.T)   # (units, features=1) → (units,units)
        pg1 = diffusion_pg1_gpu(A)

    save_dir = os.path.join(PG_DIR, model_name, split, "pg1_data")
    os.makedirs(save_dir, exist_ok=True)
    np.save(os.path.join(save_dir, f"{class_id}_{layer_name}_pg1.npy"), pg1)
    return "ok"


total_t0 = time.time()
rows     = []

for model_name, layer_names in MODELS.items():
    for split in ("correct", "incorrect"):
        for layer_name in layer_names:
            print(f"\n  {model_name}  {split}  {layer_name}")
            for class_id in range(NUM_CLASSES):
                t0     = time.time()
                status = process(model_name, split, class_id, layer_name)
                elapsed = time.time() - t0
                rows.append(dict(model=model_name, split=split, layer=layer_name,
                                 class_id=class_id, status=status,
                                 time_s=round(elapsed, 4)))
                if status == "ok":
                    print(f"    class {class_id:3d}  {elapsed:.3f}s", end="\r")

            torch.cuda.empty_cache()
            ok   = sum(1 for r in rows[-NUM_CLASSES:] if r["status"] == "ok")
            skip = NUM_CLASSES - ok
            print(f"    Done  OK={ok}  Skipped={skip}          ")

# ── Save summary ──────────────────────────────────────────────
csv_path = os.path.join(PG_DIR, "pg1_summary.csv")
with open(csv_path, "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=["model","split","layer","class_id","status","time_s"])
    w.writeheader(); w.writerows(rows)

ok_total   = sum(1 for r in rows if r["status"] == "ok")
skip_total = len(rows) - ok_total
print(f"\n  PG1 done in {time.time()-total_t0:.1f}s  "
      f"OK={ok_total}  Skipped={skip_total}")
print(f"Summary → {csv_path}")
